# Site settings
title: Заметки
email: voland62@gmail.com
description: "Место для записей."
baseurl: "/zzz" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: voland_62
github_username:  voland62

# Build settings
markdown: kramdown
